default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 2352122

development:
  <<: *default
  database: helpjuice_search_development

test:
  <<: *default
  database: helpjuice_search_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: helpjuice_search_production
  username: helpjuice_search
  # password: <%= ENV["BOOK_AN_APPOINTMENT_BACKEND_DATABASE_PASSWORD"] %>
